kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller
spec:
  replicas: 3
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: manasamurthy/spark-worker-updated-jars-1.0
          command: ["/bin/sh"]
          args: ["/usr/local/spark/spark-worker.sh"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m

